#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 13 11:27:01 2018

@author: Vincent
"""
from Calibration.DS9Utils import main

if __name__ == '__main__':
    print(__file__)
    main()
    